server:
  port: 9110
logging:
  level:
    root: info
    # 启动显示 controller 中的路径映射也就是 mapping
    org.springframework.web: TRACE

spring:
  application:
    name: eshop-datalink-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis: # 这里连接的是 twemproxy 代理地址，主机群的
    port: 1111
    host: 192.168.99.11

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  #  httpclient:
  #    enabled: true
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 10000
        readTimeout: 400000 # 3.3 * 2 分钟
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400000
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 20
      maximumSize: 1000
      maxQueueSize: -1
      queueSizeRejectionThreshold: -1
      keepAliveTimeMinutes: 2
